import {
  imageUrlWomen,
  imageUrlMen,
  gadgetUrl,
  homeFurnishUrls,
} from "./imageUrls";

export const womenClothing = [
  {
    id: "1",
    image: imageUrlWomen[0],
    title: "Anouk",
    subtitle: "Women Yellow & White Printed Kurta with Palazzos",
    stars: 4,
    rating: 150,
    oldPrice: 1799,
    newPrice: 791,
  },
  {
    id: "2",
    image: imageUrlWomen[1],
    title: "Varanga",
    subtitle: "Women Mauve & White Bandhani Printed Pure Cotton Kurta",
    stars: 4,
    rating: 197,
    oldPrice: 2799,
    newPrice: 699,
  },
  {
    id: "3",
    image: imageUrlWomen[2],
    title: "ForeEver 21",
    subtitle: "Blue & White Floral Print Ruched Styled Back Top",
    stars: 3,
    rating: 127,
    oldPrice: 1699,
    newPrice: 1529,
  },
  {
    id: "4",
    image: imageUrlWomen[3],
    title: "Marks & Spencer",
    subtitle: "Women Red & White Pure Cotton Solid Pyjamas Set",
    stars: 4,
    rating: 273,
    oldPrice: 1499,
    newPrice: 999,
  },
];

export const menClothing = [
  {
    id: "5",
    image: imageUrlMen[0],
    title: "HRX",
    subtitle: "Men Yellow Printed Cotton Pure Cotton T-shirt",
    stars: 4,
    rating: 192,
    oldPrice: 699,
    newPrice: 349,
  },
  {
    id: "6",
    image: imageUrlMen[1],
    title: "Roadster",
    subtitle: "Men Maroon & Olive Green Regular Fit Shirt",
    stars: 4,
    rating: 168,
    oldPrice: 1899,
    newPrice: 1044,
  },
  {
    id: "7",
    image: imageUrlMen[2],
    title: "ForeEver 21",
    subtitle: "Men Blue Regular Fit Faded Casual Shirt",
    stars: 5,
    rating: 327,
    oldPrice: 1799,
    newPrice: 809,
  },
  {
    id: "8",
    image: imageUrlMen[3],
    title: "Levi",
    subtitle: "Men Navy Blue Skinny Fit Stretchable Jeans",
    stars: 3,
    rating: 117,
    oldPrice: 1599,
    newPrice: 679,
  },
];

export const gadgets = [
  {
    id: "9",
    image: gadgetUrl[0],
    title: "Apple",
    subtitle: "White 2nd Gen AirPods with Charging Case",
    stars: 5,
    rating: 492,
    oldPrice: 14900,
    newPrice: 13900,
  },
  {
    id: "10",
    image: gadgetUrl[1],
    title: "Apple",
    subtitle: "Unisex Black Series 3 GPS Smart Watch",
    stars: 4,
    rating: 172,
    oldPrice: 20900,
    newPrice: 18900,
  },
  {
    id: "11",
    image: gadgetUrl[2],
    title: "OnePlus",
    subtitle: "Bullets Wireless Z Bass Edition Earphones",
    stars: 3,
    rating: 203,
    oldPrice: 2190,
    newPrice: 1999,
  },
  {
    id: "12",
    image: gadgetUrl[3],
    title: "JBL",
    subtitle: "Unisex Portable IP67 Water & Dustproof Bluetooth Speaker",
    stars: 5,
    rating: 20,
    oldPrice: 3999,
    newPrice: 3199,
  },
];

export const homeFurnish = [
  {
    id: "13",
    image: homeFurnishUrls[0],
    title: "Home Affairs",
    subtitle: "Green & White Bedsheet with 2 Pillow Covers",
    stars: 4,
    rating: 83,
    oldPrice: 1799,
    newPrice: 799,
  },
  {
    id: "14",
    image: homeFurnishUrls[1],
    title: "Aura",
    subtitle: "Pink & Orange Cotton Bedsheet with 2 Pillow Covers",
    stars: 2,
    rating: 117,
    oldPrice: 2199,
    newPrice: 769,
  },
  {
    id: "15",
    image: homeFurnishUrls[2],
    title: "A Homes Grace",
    subtitle: "Pink & White Heavy Winter Double Bed Quilt",
    stars: 4,
    rating: 147,
    oldPrice: 4500,
    newPrice: 3150,
  },
  {
    id: "16",
    image: homeFurnishUrls[3],
    title: "Home Sizzler",
    subtitle: "Yellow Cartoon Character printed Bedsheet",
    stars: 3,
    rating: 47,
    oldPrice: 1199,
    newPrice: 419,
  },
];
